import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';

// Prisma's generated Bytes fields are typed Uint8Array<ArrayBuffer>. Node's
// crypto APIs return the broader Uint8Array<ArrayBufferLike> (they could in
// principle be backed by a SharedArrayBuffer), so a narrowing cast is
// needed at the boundary — safe here since these buffers are always
// freshly allocated, never shared.
type Bytes = Uint8Array<ArrayBuffer>;

function toBytes(value: Uint8Array): Bytes {
  return Uint8Array.from(value) as Bytes;
}

export interface EncryptedPayload {
  ciphertext: Bytes;
  iv: Bytes;
  authTag: Bytes;
}

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 12; // 96-bit IV, the recommended size for GCM

// Encrypts settings marked `type: secret` (Stripe keys, SMTP passwords, ...)
// with a key that never leaves the process env — only the ciphertext is
// persisted, so a DB leak alone does not expose secrets.
@Injectable()
export class EncryptionService {
  private readonly key: Buffer;

  constructor(configService: ConfigService) {
    const masterKey = configService.getOrThrow<string>('SETTINGS_MASTER_KEY');
    this.key = Buffer.from(masterKey, 'base64');
    if (this.key.length !== 32) {
      throw new Error('SETTINGS_MASTER_KEY must decode to exactly 32 bytes');
    }
  }

  encrypt(plaintext: string): EncryptedPayload {
    const iv = randomBytes(IV_LENGTH);
    const cipher = createCipheriv(ALGORITHM, this.key, iv);
    const ciphertext = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
    const authTag = cipher.getAuthTag();
    // Copy into plain, ArrayBuffer-backed Uint8Arrays: Node's Buffer is
    // typed as Uint8Array<ArrayBufferLike> (it may be backed by a pooled
    // SharedArrayBuffer-shaped allocation), which Prisma's generated Bytes
    // field type (Uint8Array<ArrayBuffer>) rejects at the type level.
    return {
      ciphertext: toBytes(ciphertext),
      iv: toBytes(iv),
      authTag: toBytes(authTag),
    };
  }

  decrypt(payload: EncryptedPayload): string {
    const decipher = createDecipheriv(ALGORITHM, this.key, payload.iv);
    decipher.setAuthTag(payload.authTag);
    const plaintext = Buffer.concat([
      decipher.update(Buffer.from(payload.ciphertext)),
      decipher.final(),
    ]);
    return plaintext.toString('utf8');
  }

  // Never return a decrypted secret to the API by accident: mask everything
  // but the last 4 characters, matching the UI treatment described in the
  // architecture proposal.
  mask(plaintext: string): string {
    if (plaintext.length <= 4) return '••••';
    return `••••${plaintext.slice(-4)}`;
  }
}
